apiVersion: v1
kind: Namespace
metadata:
  name: ticket-backend
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: resourcequota
    namespace: ticket-backend
  spec:
    hard:
      limits.cpu: "2"
      limits.memory: 3Gi
